/* Shared footer component, injected into #global-footer-mount.
   Matches the footer in index_pink.html with full interactions. */
(function () {
    var footerMount = document.getElementById('global-footer-mount');
    if (!footerMount) return;

    var css = ''
        + '.section-footer{background-color:rgb(0,0,2) !important;}'
        + '.footer-link:hover{background-image:linear-gradient(45deg,var(--color-1),var(--color-2)) !important;-webkit-background-clip:text !important;background-clip:text !important;-webkit-text-fill-color:transparent !important;color:transparent !important;}'
        + '.text-extra-big-logo{z-index:1;width:55vw;max-width:1400px;height:auto;position:relative;-webkit-mask-image:url("images/logotype_white .svg");mask-image:url("images/logotype_white .svg");-webkit-mask-repeat:no-repeat;mask-repeat:no-repeat;-webkit-mask-size:contain;mask-size:contain;-webkit-mask-position:center;mask-position:center;background-image:radial-gradient(circle closest-side at 50% 50%,var(--color-2),transparent),linear-gradient(180deg,var(--color-1),transparent);}'
        + '.text-extra-big-logo-stroke{width:55vw;max-width:1400px;background:none;-webkit-mask-image:none;mask-image:none;opacity:0.08;}'
        + '.text-extrabig-loop-wrap{z-index:0;position:relative;}'
        + '.text-extrabig-loop-wrap::before{content:"";position:absolute;inset:0;z-index:0;background-image:radial-gradient(circle at 50% 50%,#f938a1,#500b38 55%,transparent 80%);opacity:0;transition:opacity .5s;pointer-events:none;}'
        + '.text-extrabig-loop-wrap:hover::before{opacity:0.65;}'
        + '.gradient-footer{transition:box-shadow .4s,background .4s;}'
        + '.gradient-footer:hover{background:linear-gradient(45deg,var(--color-1),var(--color-2)) !important;box-shadow:none !important;}'
        + '.footer-bottom-row{display:flex;flex-wrap:wrap;align-items:center;justify-content:space-between;gap:.75rem 1.5rem;}'
        + '.footer-location{color:#9ca3af;}'
        + '.text-sm{font-size:.875rem;line-height:1.25rem;}'
        + '.text-gray-400{color:#9ca3af;}'
        + '.footer-social-links{display:flex;align-items:center;gap:1rem;}'
        + '.footer-social-link{display:flex;color:#9ca3af;transition:color .3s ease;}'
        + '.footer-social-link:hover{color:#fff;}'
        + '.footer-social-icon{width:1.15rem;height:1.15rem;}'
        + '@media screen and (max-width:767px){'
        + '  .footer-bottom-row{display:flex !important;flex-direction:column !important;align-items:center !important;justify-content:center !important;gap:0.65rem !important;text-align:center !important;width:100% !important;padding-top:2rem !important;margin-top:2.5rem !important;border-top:1px solid rgba(255,255,255,0.08) !important;}'
        + '  .footer-location{display:flex !important;align-items:center !important;justify-content:center !important;gap:0.25rem !important;}'
        + '  .footer-social-links{display:flex !important;align-items:center !important;justify-content:center !important;gap:1.25rem !important;margin-top:0.35rem !important;}'
        + '  .footer-social-icon{width:1.35rem !important;height:1.35rem !important;}'
        + '  .footer-grid > .footer-content-grid[aria-hidden="true"]{display:none;}'
        + '}';

    var styleEl = document.createElement('style');
    styleEl.textContent = css;
    document.head.appendChild(styleEl);

    var footerHtml = ''
        + '<div mdlfy-content="component" class="footer_wrapper">'
        + '  <div class="section-footer">'
        + '    <div class="footer_09-wrapper">'
        + '      <div class="footer_wrap">'
        + '        <div class="text-extrabig-loop-wrap">'
        + '          <img class="text-extra-big-logo" src="images/logotype_white .svg" alt="Aitie" />'
        + '          <div class="gradient-footer"></div>'
        + '          <div class="text-extra-big-stroke-holder">'
        + '            <img class="text-extra-big-logo text-extra-big-logo-stroke" src="images/logotype_white .svg" alt="" aria-hidden="true" />'
        + '          </div>'
        + '        </div>'
        + '        <div class="padding-global">'
        + '          <div class="container-medium">'
        + '            <div class="padding-section-medium no-padding-top">'
        + '              <div class="footer-content-holder">'
        + '                <div><a href="/" class="footer-logo-link w-nav-brand">'
        + '                    <div class="footer-logo-wrap">'
        + '                      <div class="logo-wrap"><img loading="lazy" alt="Logo" src="images/logotype_white .svg" class="logo-image" /></div>'
        + '                    </div>'
        + '                  </a></div>'
        + '                <div class="footer-grid">'
        + '                  <div class="footer-content-grid">'
        + '                    <div class="footer_list-wrap">'
        + '                      <div class="footer_link-wrap"><a href="/" class="footer-link w-inline-block"><p>Home</p></a></div>'
        + '                      <div class="footer_link-wrap"><a href="about.html" class="footer-link w-inline-block"><p>About</p></a></div>'
        + '                      <div class="footer_link-wrap"><a href="feature.html" class="footer-link w-inline-block"><p>Features</p></a></div>'
        + '                      <div class="footer_link-wrap"><a href="blogs.html" class="footer-link w-inline-block"><p>Blogs</p></a></div>'
        + '                      <div class="footer_link-wrap"><a href="careers.html" class="footer-link w-inline-block"><p>Careers</p></a></div>'
        + '                    </div>'
        + '                  </div>'
        + '                  <div class="footer-content-grid">'
        + '                    <div class="footer_list-wrap">'
        + '                      <div class="footer_link-wrap"><a href="support.html" class="footer-link w-inline-block"><p>Support</p></a></div>'
        + '                      <div class="footer_link-wrap"><a href="privacy-policy.html" class="footer-link w-inline-block"><p>Privacy Policy</p></a></div>'
        + '                      <div class="footer_link-wrap"><a href="data-deletion.html" class="footer-link w-inline-block"><p>Data Deletion</p></a></div>'
        + '                      <div class="footer_link-wrap"><a href="terms-and-conditions.html" class="footer-link w-inline-block"><p>Terms and Conditions</p></a></div>'
        + '                    </div>'
        + '                  </div>'
        + '                  <div class="footer-content-grid">'
        + '                    <div class="footer_list-wrap">'
        + '                      <div class="footer_link-wrap"><a href="contact.html" class="footer-link w-inline-block"><p>Contact</p></a></div>'
        + '                      <div class="footer_link-wrap"><a href="waitlist.html" class="footer-link w-inline-block"><p>Join Waitlist</p></a></div>'
        + '                    </div>'
        + '                  </div>'
        + '                </div>'
        + '              </div>'
        + '              <div class="made-by-section footer-bottom-row">'
        + '                <div class="text-sm text-gray-400">© 2026 Aitie</div>'
        + '                <div class="flex flex-row items-center footer-location">'
        + '                  <svg stroke="currentColor" fill="currentColor" stroke-width="0" version="1.2" baseProfile="tiny" viewBox="0 0 24 24" class="mr-0.5 size-4 text-gray-400" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M10.368 19.102c.349 1.049 1.011 1.086 1.478.086l5.309-11.375c.467-1.002.034-1.434-.967-.967l-11.376 5.308c-1.001.467-.963 1.129.085 1.479l4.103 1.367 1.368 4.102z"></path></svg><span class="text-sm text-gray-400">Bangalore, India</span>'
        + '                </div>'
        + '                <div class="text-sm text-gray-400 footer-rights">All rights reserved</div>'
        + '                <div class="footer-social-links">'
        + '                  <a href="mailto:app@aitie.co" aria-label="Email Aitie" class="footer-social-link w-inline-block">'
        + '                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="footer-social-icon"><rect x="2" y="4" width="20" height="16" rx="2"></rect><path d="m22 6-10 7L2 6"></path></svg>'
        + '                  </a>'
        + '                  <a href="https://www.linkedin.com/company/aitie-app/" target="_blank" rel="noopener noreferrer" aria-label="Aitie on LinkedIn" class="footer-social-link w-inline-block">'
        + '                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="footer-social-icon"><path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.137 1.445-2.137 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 1 1 0-4.124 2.062 2.062 0 0 1 0 4.124zM7.114 20.452H3.558V9h3.556v11.452z"></path></svg>'
        + '                  </a>'
        + '                </div>'
        + '              </div>'
        + '            </div>'
        + '          </div>'
        + '        </div>'
        + '      </div>'
        + '    </div>'
        + '  </div>'
        + '</div>';

    footerMount.outerHTML = footerHtml;
})();
